### ISSUE TITLE
Mana and Artifice mobs are excessively spawning

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [Elfinlocks/Astral_Engineering#12]
I'm sitting here in god mode on easy at night, and it's an all-out war around me of mana and artifice spell breakers, witch hunters, mushroom guards, hulking zombies, pixies, and skeleton assassins. I'm estimating them to outnumber regular mobs 10 to 1, so I recommend if you can, please tone down their spawns. It's excessive. Have seen one spider total.

**Comment by Elfinlocks** [comment]
I believe I have fixed this, aiming to release later today

**Comment by Elfinlocks** [comment]
Fixed in release v1.1.9, please feel free to reach out if you have any further issues. 
Thanks!
