### ISSUE TITLE
Infinite power generation bug

### ISSUE THREAD

**Issue by SpaceRiceBowl** [Elfinlocks/Astral_Engineering#15]
Recently discovered that the electric motor only takes 80fe/t to output 8192su, which can drive 2 alternating dynamos to produce 192fe/t, attachted is an image. This makes infinite power at 304 fe/t per motor to dynamo setup, would reccomend increasing the power consumption of the motor to be 192fe/t at 256 rotations per second to match this.

https://imgur.com/a/g93SiQT

**Comment by Elfinlocks** [comment]
Thanks for the report, this is resolved in the latest version (v1.4.2), releasing later today
