### ISSUE TITLE
Starlight Transmutation - Diamond Ore (Oredict)

### ISSUE THREAD

**Issue by Danekjovax** [Elfinlocks/Astral_Engineering#18]
Seems that the recipe for transmuting Diamond Ore to Emerald Ore is only working with the vanilla Diamond Ore block.  Please see if this can be possible with the other stone ores, as Emerald Ore is rare to begin with, and getting vanilla ore blocks is hard given all the alternate ore bearing stone types that worldgen,  Thanks.
![2022-01-13_22 17 14](https://user-images.githubusercontent.com/10191173/149445977-538f0127-7886-4c82-8bd0-0b85b550d051.png)
![2022-01-13_22 17 19](https://user-images.githubusercontent.com/10191173/149445981-84f011b3-96f8-47f6-aae8-ccd9695de5b8.png)

**Comment by Elfinlocks** [comment]
This should be an easy fix I think, will get it done in next patch :)

**Comment by Elfinlocks** [comment]
This mod will be removed in next version, closing
