### ISSUE TITLE
Starlight Transmutation + Gem Cluster Farming + AE = Unexpected Side-Effect?

### ISSUE THREAD

**Issue by Danekjovax** [Elfinlocks/Astral_Engineering#19]
Vanilla transmutation is still at work when a gem cluster reverts Starmetal ore back to its normal state.  Given that gold ore is the base ore for making star metal, this should be adjusted to allow for gem farms. ;2)
![2022-01-13_22 33 49](https://user-images.githubusercontent.com/10191173/149447372-f2aa120f-697c-4751-82b0-33e37a38fe12.png)

**Comment by Elfinlocks** [comment]
Fixed in next version
