### ISSUE TITLE
Crafting Thermopneumatic Processing Plant with a filled Small Fluid Tank doesn't consume the tank

### ISSUE THREAD

**Issue by ApertureBear** [Elfinlocks/Astral_Engineering#22]
![image](https://user-images.githubusercontent.com/45749087/149845855-e7b8e4d7-7693-40e2-bd03-26905bd28c29.png)

![image](https://user-images.githubusercontent.com/45749087/149845882-f6d312bd-19ed-4cb3-812d-dd3832561c4f.png)

Title. Mine had 5000mB Creosote Oil in it if that is important.

**Comment by ApertureBear** [comment]
Same with Starlight Crafting Altar recipe not consuming the Bucket of Liquid Starlight.

**Comment by Elfinlocks** [comment]
Fixed in next update
