### ISSUE TITLE
Create Grinder needs to grind Unearthed ores

### ISSUE THREAD

**Issue by Danekjovax** [Elfinlocks/Astral_Engineering#23]
Regular ores can be processed in the Grinder by Create, but destroys equivalent ores in Unearthed Stone variants
![2022-01-22_15 32 57](https://user-images.githubusercontent.com/10191173/150654583-f765cfa8-b417-4f32-8356-b03ca3a20212.png)
.

**Comment by Elfinlocks** [comment]
This mod will be removed in next version, closing
