### ISSUE TITLE
Mana & Artifice: Ambiguous Recipes - Arcane Stone/Sandstone

### ISSUE THREAD

**Issue by Danekjovax** [Elfinlocks/Astral_Engineering#24]
I am trying to make Arcane Sandstone, but am only ending up with Arcane stone,  JEI says I'm doing the right thing, but M&A disagrees.  Currently I have to cheat in Arcane Sandstone to get it.  This recipe needs something more to distinguish between the recipies.  My suggestion is to change the arcane symbol.

![image](https://user-images.githubusercontent.com/10191173/151270776-05b6aa4a-e0d4-4dc1-9b5d-fed80f4d6216.png)
![image](https://user-images.githubusercontent.com/10191173/151270808-4631460d-cd71-4586-b697-73c60b9f7380.png)

![image](https://user-images.githubusercontent.com/10191173/151271154-39e1f6f6-74fc-4613-badc-630e26b1a056.png)
![image](https://user-images.githubusercontent.com/10191173/151271191-9edd3dc8-7bb0-4b5f-a89f-f8241912a639.png)

**Comment by Elfinlocks** [comment]
Confirmed bug, fixed in next patch, closing
