### ISSUE TITLE
Wizard Chalk - Enchantable?

### ISSUE THREAD

**Issue by Danekjovax** [Elfinlocks/Astral_Engineering#25]
JEI thinks so:
![image](https://user-images.githubusercontent.com/10191173/151674895-bed14c4c-c75d-4998-a2ca-530ed2e1865a.png)

But The Anvil disagrees (Book is Unbreaking III made from Enchantment Library):
![image](https://user-images.githubusercontent.com/10191173/151674911-812acd62-562d-469e-9810-ada3a37d25f4.png)

Is this a thing?

**Comment by Elfinlocks** [comment]
Reported to Mana and Artifice under #423
