### ISSUE TITLE
Quest Book Crash

### ISSUE THREAD

**Issue by blacksythe** [Elfinlocks/Astral_Engineering#30]
[crash-2022-03-21_19.23.33-client.txt](https://github.com/Elfinlocks/Astral_Engineering/files/8318689/crash-2022-03-21_19.23.33-client.txt)
Opened questbook and scrolled down and opened the railroad guides.

Instantly crashed with the following crash report.

Playing singleplayer
Version [v2.2.1]

**Comment by Elfinlocks** [comment]
Is this reproduceable, ie does it happen every time? I'm currently unable to reproduce this

**Comment by blacksythe** [comment]
Bit more testing and... 2.2.1
https://bytebin.lucko.me/5Q4H5SKBmQ
https://bytebin.lucko.me/Imn98sIvYW

New Version 2.2.2

https://bytebin.lucko.me/BuN9K0kEjp

**Comment by Elfinlocks** [comment]
I see you're running Java 17, please downgrade to Java 8 and let me know if this still occurs
