### ISSUE TITLE
Crash When Loading Resourcepack

### ISSUE THREAD

**Issue by AnzhiZhang** [Elfinlocks/Astral_Engineering#31]
I am a HongKong player. To play this modpack, I would like to load a chinese localization resourcepack, [Minecraft-Mod-Language-Package](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package). The game will crash if I load it. Here are my crash report and screen shot.
![image](https://user-images.githubusercontent.com/37402126/166107889-83cfa253-d7bc-40f0-a041-1e0c553c0403.png)
[crash-2022-04-30_21.03.24-client.txt](https://github.com/Elfinlocks/Astral_Engineering/files/8596996/crash-2022-04-30_21.03.24-client.txt)

**Comment by Elfinlocks** [comment]
Sorry but I'm not sure what is causing this - this pack leverages several resource packs - my only suggestion would be to try loading them through the OpenLoader directory in \Astral Engineering\openloader\resources
