### ISSUE TITLE
Missing Recipes for Washing Ore Dust

### ISSUE THREAD

**Issue by OJofSteel** [Elfinlocks/Astral_Engineering#33]
Issue: When using the Create Crushing Wheel, the end product is ore dust from Thermal Series. However, there are recipes missing in order to wash the Thermal Series Ore Dust into their respective nuggets. Copper Dust is the only ore dust that can be washed.

Solution: In CraftTweaker, I suggest adding compatibility recipes so all relevant ore dusts can be washed like Copper Dust. An alternative solution is to remove the Copper Dust wash recipe. 

Below I have written the recipes to wash forge tagged dusts of the following ores: Iron, Gold, Tin, Osmium, Uranium, Lead, Silver, Nickel, Zinc. The input is any forge tagged dust of that Ore type, the output is 10 guaranteed Thermal Series nuggets (where possible, otherwise Mekanism, Create, or Immersive Engineering nuggets are used), with a 50% for 5 additional nuggets.

**Recipes for CraftTweaker Ore Dust Washing** 

<recipetype:create:splashing>.addRecipe("wash_iron_dust", [<item:minecraft:iron_nugget> * 10, <item:minecraft:iron_nugget> * 5 % 50], <tag:items:forge:dusts/iron>);
<recipetype:create:splashing>.addRecipe("wash_gold_dust", [<item:minecraft:gold_nugget> * 10, <item:minecraft:gold_nugget> * 5 % 50], <tag:items:forge:dusts/gold>);
<recipetype:create:splashing>.addRecipe("wash_tin_dust", [<item:thermal:tin_nugget> * 10, <item:thermal:tin_nugget> * 5 % 50], <tag:items:forge:dusts/tin>);
<recipetype:create:splashing>.addRecipe("wash_osmium_dust", [<item:mekanism:nugget_osmium> * 10, <item:mekanism:nugget_osmium> * 5 % 50], <tag:items:forge:dusts/osmium>);
<recipetype:create:splashing>.addRecipe("wash_urnaium_dust", [<item:immersiveengineering:nugget_uranium> * 10, <item:immersiveengineering:nugget_uranium> * 5 % 50], <tag:items:forge:dusts/uranium>);
<recipetype:create:splashing>.addRecipe("wash_lead_dust", [<item:thermal:lead_nugget> * 10, <item:thermal:lead_nugget> * 5 % 50], <tag:items:forge:dusts/lead>);
<recipetype:create:splashing>.addRecipe("wash_silver_dust", [<item:thermal:silver_nugget> * 10, <item:thermal:silver_nugget> * 5 % 50], <tag:items:forge:dusts/silver>);
<recipetype:create:splashing>.addRecipe("wash_nickel_dust", [<item:thermal:nickel_nugget> * 10, <item:thermal:nickel_nugget> * 5 % 50], <tag:items:forge:dusts/nickel>);
<recipetype:create:splashing>.addRecipe("wash_zinc_dust", [<item:create:zinc_nugget> * 10, <item:create:zinc_nugget> * 5 % 50], <tag:items:forge:dusts/zinc>);

**Comment by OJofSteel** [comment]
Forgive me, the osmium recipe is wrong. The correct one is

<recipetype:create:splashing>.addRecipe("wash_osmium_dust", [<item:mekanism:nugget_osmium> * 10, <item:mekanism:nugget_osmium> * 5 % 50], <tag:items:forge:dusts/osmium>);

**Comment by Elfinlocks** [comment]
Thanks for the writeup! Adding this to upcoming patch
