### ISSUE TITLE
Issues with Questbook Tasks that require you to visit a dimension

### ISSUE THREAD

**Issue by JohanniklasLp** [Elfinlocks/Astral_Engineering#34]
Description:
If you complete a task that requires you to visit a dimension, like the end or the twilight forest, but you have not completed the prerequisite quest(s), the task will already show as completed. When you then complete the prerequisite quests, the task will be completed, the quest will be at 100% completion, but the quest does not count as completed.

Steps to reproduce (Twilight Forest example):
1. go into the Twilight Forest dimension
2. (Force)Complete the Terrestrial Agglomeration Quest
3. The Twilight Forest Quest will not complete even though all tasks and prerequisite quests are completed

Expected behaviour:
The quests should be completed

Additional Information:
I have only seen this issue with the task type that require you to go into a certain dimension, the other task types do not seem to have this issue. A potential fix would thus be to change the task to require the advancements for reaching the end/twilight forest. (I have not checked if there are any more dimension tasks in the Questbook anf if that would work for those)

Picture showing the bugged Twilight Forest Quest (it doesn't have the 'completed' checkmark and I cannot collect the rewards):
![grafik](https://user-images.githubusercontent.com/57828910/187539005-225de281-8698-40e0-8447-3ead563cbe8b.png)

**Comment by JohanniklasLp** [comment]
The bigger quests in the solar sightseeing chapter (excluding the beginning one) are dimension task quests as well. I have not tested if those have the same issue yet, but I assume they do.

**Comment by Elfinlocks** [comment]
I've changed the dimensional visit quests to checkmarks instead of requiring the dimension visit for next update. Unfortunately this is a bug with FTB Quests. Thanks for reporting!
