### ISSUE TITLE
Unnecessary Questgating

### ISSUE THREAD

**Issue by JohanniklasLp** [Elfinlocks/Astral_Engineering#35]
Some of the quests have prerequisite quests that, in my opinion, do not make a lot of sense.
The ones I have found so far (I have mostly played through the magic part so far, and have only rushed the Arc Furnace to continue magic, so I don't know a lot about the Tech part of the Questbook) are:
- Integrated Circuits being gated by the Alternator even though they only require progress up to cured rubber, maybe up to the mechanical belt (or maybe plates for the brass hand but you can make plates as soon as you have the press)
- The arc furnace being gated by the metallurgic Infuser even though it only requires progress up to the engineering blocks quest (plus potentially parts of the wire quests to get the electricity to the furnace), or, since that is an existing quest, the industrial squeezer for the electrodes. I can see it being close to the power problems quest chain since it requires a lot of power, but questgating it with the Infuser makes no sense since none of the components needed to create it require the Infuser
- The twilight forest quest is gated by the terrestrial agglomeration plate quest, though getting into the twilight forest only requires a mana diamond, which is the quest before the TAP quest and doesn't require you to get to Tier 4 in Mana and Artifice
- The mana infuser quest is gated by the end dimension quest, even though it doesn't need anything that you can only get in the end. The only advantage getting to the end has is easy access to Ender Pearls
- The terrasteel armor is gated by Gaia Spirits. You only need progress up to Terrasteel Ingots to create them. Alfsteel Armor is by proxy also gated by Gaia Spirits, but, besides terrasteel armor, only require alfsteel

I have also noticed some things in the reverse sense, but I don't think those are as important, if at all:
- Summoning the Gaia Guardian requires Alfsteel (for the pylons), but is only gated by the portal to Alfheim (and resonating gems)
- The Flügel Tiara and the Orechid need Gaia Spirits, but the quests are only gated by Terrasteel
- The Mana-Infuser needs resonating gems, though I understand why that connection doesn't exist designwise

Things that make sense but are still noteworthy:
- Manasteel can be created directly from Vinteum Ingots by using the Vinteum Block -> Manasteel Block recipe. I don't know if that is intended.
- If you use the Mana Fluxfield you do not need the Alternating Dynamo which is gating part of the Early Industry Chapter
- Aluminum Ore can be mined in the Alfheim Dimension, making parts of the questchain in Advanced Industry, at least for Aluminium Ingots themselves, unnecessary if you go the magic route

**Comment by Elfinlocks** [comment]
I've done some reworking to the quests and item recipes based on these requirements, thanks!
