### ISSUE TITLE
Seeds unavailable & missing

### ISSUE THREAD

**Issue by Cenadra** [Elfinlocks/Astral_Engineering#40]
I have searched the our new world for onion seeds from crock pot mod and onions to plant from farmer's delight mod. No wild onion or onions can be found anywhere (not in dungeons, village farms, planted in the wild, or in chests) please help.

**Comment by Elfinlocks** [comment]
This has been fixed in v2.4.5, which is now on Curseforge. I unfortunately can't add the wild crops as they cause a weird crashing bug, but the crops are now available as loot in villages and through the Market block.

**Comment by Cenadra** [comment]
They must be exceedingly rare, unfortunately, as I have visited one dozen villages to no avail. Also, they are not available through the market from either mod. On Feb 10, 2023, at 6:06 AM, Elfinlocks ***@***.***> wrote:﻿
Closed #40 as completed.

**Comment by Elfinlocks** [comment]
Did you update your pack version?
