### ISSUE TITLE
Every New Tardis Mod Spawn defaulted to 0%

### ISSUE THREAD

**Issue by ghost** [Elfinlocks/Astral_Engineering#43]
Spent an hour looking for a tardis in creative to see how hard it would be. Only to check the config and see everything is set to 0 by default.

**Comment by Elfinlocks** [comment]
This is intentional.

**Comment by ghost** [comment]
Ok yeah…why.

**Comment by Elfinlocks** [comment]
Because this is the way I designed the modpack. The TARDIS allows interdimensional travel, which is a major progression lock in this modpack, which you would know if you had played it, or looked at any of the quests, at all. Please refrain from spamming my Github with further non-issues.

**Comment by ghost** [comment]
Thank you for the answer and sorry for bothering you. 

Guess I’m behind the times but I’ve never had a modpack lock out the progression of a mod entirely through the quest system so I just didn’t bother looking since I don’t typically care about quests.  

That was the most standout mod to me and was my main reason for picking it. Guess I could always just edit the config since I much prefer the natural difficulty of finding and caring for it. 

Ty again.
